### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by pplegends** [Zenithsiz/ddw3#1]
Can I build the DW2003 game from this repository (https://gitea.filipejr.com/Zenithsiz/ddw3)? 
Is it ready to build, or is it still a work in progress?

I want to add my own language. Should I create another toml files or just edit from one of the existing  toml files language. Thanks

**Comment by Zenithsiz** [comment]
The repo can already build the full dw2003 game, yes, although you will need all the tools listed in `zbuild.yaml`, as well as the license files (see README for more information on these).

As for adding a new language, since we don't have the code reverse-engineered quite yet, you'd have to replace an existing language, but that should be doable just by editing the lang files, and if you really wanted to, editing the language selection image from the start of the game (although I haven't found that image yet).

**Comment by pplegends** [comment]
i installed as, ld, objcopy, mkpsxiso, cargo(nightly one), sed, sha256sum, rm, mkdir, cp, touch, truncate, python, pillow, pyelftools, toml, yq. as for the licenses i somehow got it. I am trying to build with zbuild 0.1.7. when i use zbuild, it seems that it can't build bin file and only builds some of the dependencies. am i missing something?
![zbuild only](https://github.com/user-attachments/assets/11ba904d-3960-43b8-8255-b48a163d6f5e)
![zbuild compare](https://github.com/user-attachments/assets/244f5bf1-2bc8-4111-a233-d513a3cf98a0)

**Comment by Zenithsiz** [comment]
It seems that `mkpsxiso` failed in the first one, and somehow `mktim` failed on the second one. The second one could only really fail on the input file missing (or I/O errors on writing the output, but it's probably not that).

Did you download lfs files from the repo? If not, you'll need to setup git-lfs first, then `git lfs fetch` to download all files.

**Comment by pplegends** [comment]
I just finished git lfs fetch and build the repo again. 

It seems that 25k targets build successfully when its checked 61k target, however there is dw3.bin and .cue file in the iso directory, the language bin was successfully build this time. 

I notice new error like this: Unable to spawn ["mips-elf-as" "-MD" "build/asm/dw2003/pro/
Does this mean I need to reinstall the GNU assembler?

Here is the full error log, Thank you for your help:
zbuild
WARNING: 'source' attribute for subdirectory 'AAA' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'PRO' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'DAT' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'CARD' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'COMMON' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'COUNTRY' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'ENG' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'FRA' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'GER' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'ITA' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'JPN' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'SPN' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'USA' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'DGLB' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'EFFECT' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'FIELD' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'SPRT' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'STAGE' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'MCARD' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'MODEL' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'NAMEENT' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'SCREEN' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'SOUND' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'TEXT' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'TRAINING' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'Z_STAGE' is invalid or empty.
WARNING: 'source' attribute for subdirectory 'STR' is invalid or empty.
warning: the --out-dir flag has been changed to --artifact-dir
warning: the --out-dir flag has been changed to --artifact-dir
    Blocking waiting for file lock on package cache
warning: the --out-dir flag has been changed to --artifact-dir
warning: the --out-dir flag has been changed to --artifact-dir
warning: the --out-dir flag has been changed to --artifact-dir
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
warning: the --out-dir flag has been changed to --artifact-dir
warning: the --out-dir flag has been changed to --artifact-dir
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
    Finished `release` profile [optimized] target(s) in 0.44s
    Finished `release` profile [optimized] target(s) in 0.45s
    Finished `release` profile [optimized] target(s) in 0.46s
    Finished `release` profile [optimized] target(s) in 0.46s
    Finished `release` profile [optimized] target(s) in 0.47s
    Finished `release` profile [optimized] target(s) in 0.46s
    Finished `release` profile [optimized] target(s) in 0.47s
warning: the --out-dir flag has been changed to --artifact-dir
warning: the --out-dir flag has been changed to --artifact-dir
warning: the --out-dir flag has been changed to --artifact-dir
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
warning: the --out-dir flag has been changed to --artifact-dir
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
warning: the --out-dir flag has been changed to --artifact-dir
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
    Finished `release` profile [optimized] target(s) in 0.17s
    Finished `release` profile [optimized] target(s) in 0.18s
    Finished `release` profile [optimized] target(s) in 0.19s
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Finished `release` profile [optimized] target(s) in 0.10s
    Finished `release` profile [optimized] target(s) in 0.19s
file: $(dw3_psx_iso)
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
error: "/home/pplegends/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
error: "/home/pplegends/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
error: "/home/pplegends/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
error: "/home/pplegends/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
2024-08-11T05:06:27.921594Z ERROR zbuild: Unable to build target target=file: $(dw2003_psx_iso) err=Unable to build dependencies file "build/iso/dw2003.bin.d"
└─Multiple errors:
  ├─Unable to build target file: build/raw_exe/dw2003/pro/sdigiedt.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/sdigiedt.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/sdigiedt.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/sdigiedt.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/sdigiedt.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/sdigiedt.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_sdigiedt.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_sdigiedt" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(1 irrelevant errors)
  │         └─(1 irrelevant errors)
  ├─Unable to build target file: build/raw_exe/dw2003/pro/stfgtrep.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/stfgtrep.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/stfgtrep.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/stfgtrep.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/stfgtrep.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/stfgtrep.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_stfgtrep.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_stfgtrep" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(2 irrelevant errors)
  │         └─(1 irrelevant errors)
  ├─Unable to build target file: build/raw_exe/dw2003/pro/fieldstg.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/fieldstg.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/fieldstg.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/fieldstg.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/fieldstg.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/fieldstg.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_fieldstg.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_fieldstg" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(1 irrelevant errors)
  │         └─(1 irrelevant errors)
  ├─Unable to build target file: build/raw_exe/dw2003/pro/stgtrain.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/stgtrain.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/stgtrain.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/stgtrain.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/stgtrain.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/stgtrain.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/asm/dw2003/pro/stgtrain.o
  │         │     │ └─Unable to build rule asm
  │         │     │   └─Unable to spawn ["mips-elf-as" "-MD" "build/asm/dw2003/pro/stgtrain.d" "asm/dw2003/pro/stgtrain.s" "-o" "build/asm/dw2003/pro/stgtrain.o" "-EL" "-mabi=32" "-mips1" "-march=r3000" "-msoft-float" "-g" "-Iasm/" "-I./" "-Iasm/dw2003/pro" "--strip-local-absolute"]
  │         │     │     └─No such file or directory (os error 2)
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_stgtrain.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_stgtrain" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(5 irrelevant errors)
  │         └─(1 irrelevant errors)
  └─(1418 irrelevant errors)
Note: 1431 irrelevant errors were hidden, set `ZBUILD_SHOW_IRRELEVANT_ERRS=1` to show them
2024-08-11T05:06:27.999724Z  INFO zbuild: Built 25669 targets
2024-08-11T05:06:27.999738Z  INFO zbuild: Checked 61923 targets
2024-08-11T05:06:27.999740Z ERROR zbuild: One or more builds failed:
2024-08-11T05:06:27.999744Z ERROR zbuild: Failed to build target file: $(dw2003_psx_iso) err=Unable to build dependencies file "build/iso/dw2003.bin.d"
└─Multiple errors:
  ├─Unable to build target file: build/raw_exe/dw2003/pro/sdigiedt.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/sdigiedt.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/sdigiedt.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/sdigiedt.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/sdigiedt.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/sdigiedt.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_sdigiedt.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_sdigiedt" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(1 irrelevant errors)
  │         └─(1 irrelevant errors)
  ├─Unable to build target file: build/raw_exe/dw2003/pro/stfgtrep.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/stfgtrep.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/stfgtrep.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/stfgtrep.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/stfgtrep.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/stfgtrep.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_stfgtrep.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_stfgtrep" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(2 irrelevant errors)
  │         └─(1 irrelevant errors)
  ├─Unable to build target file: build/raw_exe/dw2003/pro/fieldstg.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/fieldstg.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/fieldstg.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/fieldstg.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/fieldstg.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/fieldstg.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_fieldstg.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_fieldstg" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(1 irrelevant errors)
  │         └─(1 irrelevant errors)
  ├─Unable to build target file: build/raw_exe/dw2003/pro/stgtrain.bin
  │ └─Unable to build dependencies file "build/raw_exe/dw2003/pro/stgtrain.d"
  │   └─Unable to build target file: build/lib/dw2003/pro/stgtrain.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/pro/stgtrain.d"
  │       └─Multiple errors:
  │         ├─Unable to build target file: build/elf/dw2003/pro/stgtrain.elf
  │         │ └─Unable to build dependencies file "build/elf/dw2003/pro/stgtrain.d"
  │         │   └─Multiple errors:
  │         │     ├─Unable to build target file: build/asm/dw2003/pro/stgtrain.o
  │         │     │ └─Unable to build rule asm
  │         │     │   └─Unable to spawn ["mips-elf-as" "-MD" "build/asm/dw2003/pro/stgtrain.d" "asm/dw2003/pro/stgtrain.s" "-o" "build/asm/dw2003/pro/stgtrain.o" "-EL" "-mabi=32" "-mips1" "-march=r3000" "-msoft-float" "-g" "-Iasm/" "-I./" "-Iasm/dw2003/pro" "--strip-local-absolute"]
  │         │     │     └─No such file or directory (os error 2)
  │         │     ├─Unable to build target file: build/rust/dw2003_pro_stgtrain.a
  │         │     │ └─Unable to build rule rust_lib
  │         │     │   └─Command failed ["cargo" "build" "--release" "--package=dw2003_pro_stgtrain" "-Z=unstable-options"]
  │         │     │     └─process exited unsuccessfully: exit status: 101
  │         │     └─(5 irrelevant errors)
  │         └─(1 irrelevant errors)
  └─(1418 irrelevant errors)
Note: 1431 irrelevant errors were hidden, set `ZBUILD_SHOW_IRRELEVANT_ERRS=1` to show them
Error: Exiting with non-0 due to failed builds

**Comment by pplegends** [comment]
I installed GNU assembler 23.9 and it solve the previous error, but i still got error in dmw2003, please help me if you know what the issue is, Thank you

Additionally, I will try to match the tool versions specified in the YAML files. I also tried playing dw3.bin, it runs but the first FMV seems to have no sound.

error:
warning: static `LBA_SYSTEM_CNF_IMPL` is never used
     --> dw2003_exe_data/src/data.rs:22987:13
      |
22987 |     static mut LBA_SYSTEM_CNF_IMPL: u8; // 23
      |                ^^^^^^^^^^^^^^^^^^^
      |
      = note: `#[warn(dead_code)]` on by default

warning: static `LBA_SLES_039_36_IMPL` is never used
     --> dw2003_exe_data/src/data.rs:22988:13
      |
22988 |     static mut LBA_SLES_039_36_IMPL: u8; // 24
      |                ^^^^^^^^^^^^^^^^^^^^

warning: static `LBA_DUMMY_IMPL` is never used
     --> dw2003_exe_data/src/data.rs:22989:13
      |
22989 |     static mut LBA_DUMMY_IMPL: u8; // 276901
      |                ^^^^^^^^^^^^^^

warning: `dw2003_exe_data` (lib) generated 3 warnings
   Compiling dw2003_exe v0.1.0 (/home/pplegends/git-build/zen/ddw3/rust/dw2003_exe)
warning: MIPS-I support is experimental
    Finished `release` profile [optimized] target(s) in 14.52s
warning: MIPS-I support is experimental
warning: MIPS-I support is experimental
warning: MIPS-I support is experimental
warning: MIPS-I support is experimental
warning: MIPS-I support is experimental
   Compiling dw2003_pro_fieldstg v0.1.0 (/home/pplegends/git-build/zen/ddw3/rust/dw2003_pro_fieldstg)
warning: MIPS-I support is experimental
    Finished `release` profile [optimized] target(s) in 14.57s
Error: License file was too big: 28224/1972
2024-08-11T08:10:35.644886Z ERROR zbuild: Unable to build target target=file: $(dw2003_psx_iso) err=Unable to build dependencies file "build/iso/dw2003.bin.d"
└─Multiple errors:
  ├─Unable to build target file: build/psexe/dw2003/exe.psexe
  │ └─Unable to build dependencies file "build/psexe/dw2003/exe.d"
  │   └─Unable to build target file: build/lib/dw2003/exe.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/exe.d"
  │       └─Unable to build target file: build/iso/dw2003-bootstrap.lba.syms
  │         └─Unable to build target file: build/iso/dw2003-bootstrap.lba.c
  │           └─Unable to build dependencies file "build/iso/dw2003-bootstrap.lba.d"
  │             └─Multiple errors:
  │               ├─Unable to build target file: build/psexe/dw2003/exe-bootstrap.psexe
  │               │ └─Unable to build rule psexe
  │               │   └─Command failed ["build/tools/mkpsexe" "psexe/dw2003/exe-bootstrap.toml" "--output=build/psexe/dw2003/exe-bootstrap.psexe"]
  │               │     └─process exited unsuccessfully: exit status: 1
  │               └─(316 irrelevant errors)
  └─(316 irrelevant errors)
Note: 632 irrelevant errors were hidden, set `ZBUILD_SHOW_IRRELEVANT_ERRS=1` to show them
2024-08-11T08:10:35.723444Z  INFO zbuild: Built 68996 targets
2024-08-11T08:10:35.723455Z  INFO zbuild: Checked 69320 targets
2024-08-11T08:10:35.723458Z ERROR zbuild: One or more builds failed:
2024-08-11T08:10:35.723461Z ERROR zbuild: Failed to build target file: $(dw2003_psx_iso) err=Unable to build dependencies file "build/iso/dw2003.bin.d"
└─Multiple errors:
  ├─Unable to build target file: build/psexe/dw2003/exe.psexe
  │ └─Unable to build dependencies file "build/psexe/dw2003/exe.d"
  │   └─Unable to build target file: build/lib/dw2003/exe.elf
  │     └─Unable to build dependencies file "build/lib/dw2003/exe.d"
  │       └─Unable to build target file: build/iso/dw2003-bootstrap.lba.syms
  │         └─Unable to build target file: build/iso/dw2003-bootstrap.lba.c
  │           └─Unable to build dependencies file "build/iso/dw2003-bootstrap.lba.d"
  │             └─Multiple errors:
  │               ├─Unable to build target file: build/psexe/dw2003/exe-bootstrap.psexe
  │               │ └─Unable to build rule psexe
  │               │   └─Command failed ["build/tools/mkpsexe" "psexe/dw2003/exe-bootstrap.toml" "--output=build/psexe/dw2003/exe-bootstrap.psexe"]
  │               │     └─process exited unsuccessfully: exit status: 1
  │               └─(316 irrelevant errors)
  └─(316 irrelevant errors)
Note: 632 irrelevant errors were hidden, set `ZBUILD_SHOW_IRRELEVANT_ERRS=1` to show them
Error: Exiting with non-0 due to failed builds

**Comment by pplegends** [comment]
I finally succeeded in building dmw2003.bin, thanks! 
It seems the license was the culprit. However, the FMV still has no sound, just like dw3.bin. How do I fix this?

Also, when changing the language, do I need to maintain the same word count as the one I replace?

**Comment by Zenithsiz** [comment]
I'm glad you got it running, and sorry for the issues caused by lack of documentation.

As for the FMV sound, I confirmed it also happens to me, so it seems I somehow forgot to dump the FMV tracks (I assumed they were included in the video file, but it seems not). I'll have them included once I figure out how they're encoded in the iso.

And as for the language, it's relevant to know that the game accesses the files in the iso not by path (like "AAA/DAT/..."), but instead by sector position, which can change if the files get bigger.

Fortunately, the strings themselves are aligned to 4 bytes (with a null at the end auto-added by the build program), so if a string has, for e.g., 5 letters, it occupies 8 bytes (5 for the letters, 3 for the nulls to make a 4-aligned string), so you can use up to 7 letters without shifting anything, leaving 1 null. If you did 8 letters, it'd occupy 12 bytes, since it'd need to use all 4 bytes for the null.

Also since iso sectors are aligned to 2048 bytes (if I remember correctly), you should have a bit of leeway in each language file (anywhere from 0 bytes to 2045 bytes).

I've also recently made the game auto-calculate new LBAs (i.e. sector positions) based on the files in the repo, so theoretically you should be able to make it as big as you want, but I haven't been able to test this, and it might cause some issues with things moving in memory instead.

**Comment by pplegends** [comment]
it's not that, it's just that I'm not very familiar with the Linux environment. Thanks for this work, btw.

As for the FMV, it seems like only the first one doesn't have sound. I played a little bit yesterday, and the second FMV already has sound. I don't know if the other FMVs have sound or not, but I'll check as I play later.

I'll start replacing the language to figure out what I can and can't do with it. Once again, thank you very much for this work.
