### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by pplegends** [Zenithsiz/ddw3#2]
Hello, sorry to bother you again. I reinstalled my OS, and after that, I encountered an error like this:

Is the issue related to the PNG error or something else?
=================================================================================
Error: Error: Unable to read imageUnable to read imageliteral                                    

Caused by:

Caused by:

 Error:   Unable to read image  

Caused by:  
 00 : :  Format error decoding Format error decoding  PngPng : : 0Invalid PNG signature.Invalid PNG signature.: 

Format error decoding   Png  :   Invalid PNG signature.  
11 : :  Invalid PNG signature.Error: Invalid PNG signature. 
Unable to read image
 

Caused by:1
:  Invalid PNG signature. 
  0: Format error decoding Png: Invalid PNG signature.
    1: Invalid PNG signature.
Error: Unable to read image

Caused by:
    0: Format error decoding Png: Invalid PNG signature.
    1: Invalid PNG signature.
Error: Error: Unable to read image

Caused by:Unable to read image

Caused by: 
      0 : 0Format error decoding : PngFormat error decoding : PngInvalid PNG signature.: 
Invalid PNG signature. 
      1 : 1Invalid PNG signature.: 
Invalid PNG signature.
Error: Unable to read image

Caused by:
    0: Format error decoding Png: Invalid PNG signature.
    1: Invalid PNG signature.
Error: Unable to read image

Caused by:
    0: Format error decoding Png: Invalid PNG signature.
    1: Error: Invalid PNG signature.Unable to read image

Caused by:
    0: Format error decoding Png: Invalid PNG signature.
    1: Invalid PNG signature.
Error: Unable to read image

Caused by:
    0: Format error decoding Png: Invalid PNG signature.
    1: Invalid PNG signature.
Error: Unable to read image

Caused by:
    0: Format error decoding Png: Invalid PNG signature.
    1: Invalid PNG signature.

And error like this:
=================================================================================
2024-09-01T12:01:35.953615Z ERROR zbuild: Unable to build target target=file: $(dw2003_psx_iso) err=Unable to build dependencies file "build/iso/dw2003.bin.d"
└─Multiple errors:
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p078hgmk.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p078hgmk.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p078hgmk/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p078hgmk/0.toml" "--output=build/tim/dw2003/field/sprite/p078hgmk/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p078hgmk/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p078hgmk/1.toml" "--output=build/tim/dw2003/field/sprite/p078hgmk/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p086aird.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p086aird.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p086aird/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p086aird/0.toml" "--output=build/tim/dw2003/field/sprite/p086aird/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p086aird/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p086aird/1.toml" "--output=build/tim/dw2003/field/sprite/p086aird/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p087ters.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p087ters.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p087ters/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p087ters/0.toml" "--output=build/tim/dw2003/field/sprite/p087ters/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p087ters/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p087ters/1.toml" "--output=build/tim/dw2003/field/sprite/p087ters/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p088gabs.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p088gabs.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p088gabs/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p088gabs/0.toml" "--output=build/tim/dw2003/field/sprite/p088gabs/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p088gabs/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p088gabs/1.toml" "--output=build/tim/dw2003/field/sprite/p088gabs/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p089pyos.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p089pyos.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p089pyos/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p089pyos/1.toml" "--output=build/tim/dw2003/field/sprite/p089pyos/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p089pyos/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p089pyos/0.toml" "--output=build/tim/dw2003/field/sprite/p089pyos/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p093hanm.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p093hanm.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p093hanm/3.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p093hanm/3.toml" "--output=build/tim/dw2003/field/sprite/p093hanm/3.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(5 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p109mthi.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p109mthi.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p109mthi/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p109mthi/0.toml" "--output=build/tim/dw2003/field/sprite/p109mthi/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(2 irrelevant errors)
  └─(704 irrelevant errors)
Note: 716 irrelevant errors were hidden, set `ZBUILD_SHOW_IRRELEVANT_ERRS=1` to show them
2024-09-01T12:01:35.976345Z  INFO zbuild: Built 21 targets
2024-09-01T12:01:35.976354Z  INFO zbuild: Checked 30 targets
2024-09-01T12:01:35.976356Z ERROR zbuild: One or more builds failed:
2024-09-01T12:01:35.976359Z ERROR zbuild: Failed to build target file: $(dw2003_psx_iso) err=Unable to build dependencies file "build/iso/dw2003.bin.d"
└─Multiple errors:
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p078hgmk.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p078hgmk.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p078hgmk/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p078hgmk/0.toml" "--output=build/tim/dw2003/field/sprite/p078hgmk/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p078hgmk/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p078hgmk/1.toml" "--output=build/tim/dw2003/field/sprite/p078hgmk/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p086aird.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p086aird.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p086aird/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p086aird/0.toml" "--output=build/tim/dw2003/field/sprite/p086aird/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p086aird/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p086aird/1.toml" "--output=build/tim/dw2003/field/sprite/p086aird/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p087ters.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p087ters.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p087ters/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p087ters/0.toml" "--output=build/tim/dw2003/field/sprite/p087ters/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p087ters/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p087ters/1.toml" "--output=build/tim/dw2003/field/sprite/p087ters/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p088gabs.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p088gabs.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p088gabs/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p088gabs/0.toml" "--output=build/tim/dw2003/field/sprite/p088gabs/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p088gabs/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p088gabs/1.toml" "--output=build/tim/dw2003/field/sprite/p088gabs/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p089pyos.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p089pyos.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p089pyos/1.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p089pyos/1.toml" "--output=build/tim/dw2003/field/sprite/p089pyos/1.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p089pyos/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p089pyos/0.toml" "--output=build/tim/dw2003/field/sprite/p089pyos/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(1 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p093hanm.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p093hanm.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p093hanm/3.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p093hanm/3.toml" "--output=build/tim/dw2003/field/sprite/p093hanm/3.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(5 irrelevant errors)
  ├─Unable to build target file: build/pack/dw2003/field/sprite/p109mthi.bin
  │ └─Unable to build dependencies file "build/pack/dw2003/field/sprite/p109mthi.d"
  │   └─Multiple errors:
  │     ├─Unable to build target file: build/tim/dw2003/field/sprite/p109mthi/0.tim
  │     │ └─Unable to build rule tim
  │     │   └─Command failed ["build/tools/mktim" "tim/dw2003/field/sprite/p109mthi/0.toml" "--output=build/tim/dw2003/field/sprite/p109mthi/0.tim"]
  │     │     └─process exited unsuccessfully: exit status: 1
  │     └─(2 irrelevant errors)
  └─(704 irrelevant errors)
Note: 716 irrelevant errors were hidden, set `ZBUILD_SHOW_IRRELEVANT_ERRS=1` to show them
Error: Exiting with non-0 due to failed builds

**Comment by Zenithsiz** [comment]
From what I can tell, it seems that `mktim` thinks the png files are corrupt somehow. 

I believe this is to do with `git-lfs`. When you don't have `git-lfs` installed and you clone a repo with lfs files, all the binary files are instead downloaded as text files with a "link" to the actual file.

Can you try to install `git-lfs`, then `git lfs fetch` to download all files, then try again?

**Comment by pplegends** [comment]
That's it, I forgot to install git lfs. I want to edit the first language selection, what do I need to do that?

**Comment by Zenithsiz** [comment]
I've recently extracted the file with the language selection.

It's located in `tim/dw2003/country/cntselwn/1/0.png`. However, you'll need to be careful editing it. Either restrict yourself to existing colors (**exactly** the same existing colors) when you edit it.

If this is too restrictive, you can probably edit the `toml` file besides it to something like this:

```toml
bpp = "Color24"

[img]
pos = [0, 0]
path = "0.png"
```

This switches it from using a `CLUT` to encoding all the colors, but it's possible the title screen doesn't support doing that for whatever reason, so this approach might not work, you'd need to test it.

**Comment by pplegends** [comment]
What are the rules for editing this? I tried editing it by just swapping the flag within the image, but it gave me an error during the zbuild process.


Ahh, my bad. It looks like I didn’t edit it the correct way. I can edit it now as long as I just use the existing colors. Thank you very much.
